spring:
  application:
    name: hotel-inventory-backend

  datasource:
    url: jdbc:mysql://localhost:3306/hotel_inventory?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: student
    password: student123

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080

jwt:
  secret: YourSuperSecretKeyAtLeast32CharsLong123!
  expirationMinutes: 60
